### PR TITLE
Flush newly generated seed to filesystem

### LINKED ISSUE #303: Seed provided with node.seed not stored, when goshimmer crashes at very first start
## Bug description

GoShimmer does not store the provided node.seed in the peer database, when GoShimmer **is started the very first time** and does **not shutdown gracefully**.

hive.io reads the seed from command line and keeps the seed in the memory. The seed is only stored, when GoShimmer stops gracefully:

`2021-12-02T18:33:59+01:00       INFO    Peer    peer/plugin.go:68       saved identity 9bUpriDHjQDa`

If GoShimmer crashes when running the very first time, the peerdb does not store the seed. When you start GoShimmer the second time GoShimmer checks, if a seed is stored in the peerdb. If no seed is stored it generates a new one. This results in an error:

```
2021-12-02T18:43:26+01:00       FATAL   Peer    peer/plugin.go:100      private key derived from the seed defined in the config does not correspond with the already stored private key in the database: identities - pub keys (cfg/db): 9bUpriDHjQDaQhRpaPYsn94rVWX18WPnXSZV5xX7GxEx vs. DQgLQkcDBRzdkLEshBJzzwdX8YRQ6SuR9LhbAxngyR6S
```

## Go version

- Go version: go1.17.3 linux/amd64

## Hardware specification

What hardware are you using?

- Operating system: Docker and Ubuntu
- RAM: 32 GB
- Cores: 8
- Device: Workstation

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Make sure no peerdb exists: rm peerdb/*
2. Start GoShimmer with node.seed:  ./goshimmer --node.seed="base64:YOUR-SEED"
3. Kill GoShimmer: kill -SIGKILL 58168
4. Start GoShimmer with node.seed:  ./goshimmer --node.seed="base64:YOUR-SEED"
5. Error: private key derived from the seed defined in the config does not correspond with the already stored private key in the database

## Expected behaviour

Correct node.seed is stored in peerdb and GoShimmer starts without error.

## Actual behaviour

GoShimmer crashes after 

## Errors
```
2021-12-02T18:51:16+01:00       INFO    Node    banner/plugin.go:40     GoShimmer version v0.8.3 ...
2021-12-02T18:51:16+01:00       INFO    Node    banner/plugin.go:41     Loading plugins ...
2021-12-02T18:51:16+01:00       INFO    Node    node/node.go:107        Loading Plugin: Banner ... done
2021-12-02T18:51:16+01:00       INFO    Node    node/node.go:107        Loading Plugin: Config ... done
2021-12-02T18:51:16+01:00       INFO    Node    node/node.go:107        Loading Plugin: Logger ... done
2021-12-02T18:51:16+01:00       INFO    Node    node/node.go:107        Loading Plugin: CLI ... done
2021-12-02T18:51:16+01:00       INFO    Node    node/node.go:107        Loading Plugin: GracefulShutdown ... done
2021-12-02T18:51:16+01:00       INFO    Database        database/plugin.go:136  Running database garbage collection...
2021-12-02T18:51:16+01:00       INFO    Database        database/plugin.go:142  Database garbage collection done, took 1.159082ms...
2021-12-02T18:51:16+01:00       INFO    Node    node/node.go:107        Loading Plugin: Database ... done
2021-12-02T18:51:16+01:00       FATAL   Peer    peer/plugin.go:100      private key derived from the seed defined in the config does not correspond with the already stored private key in the database: identities - pub keys (cfg/db): 9bUpriDHjQDaQhRpaPYsn94rVWX18WPnXSZV5xX7GxEx vs. 7sqXTjVPsURM4Gc9oKgLdnJdURFBVasHJqGxDozqkyhi
github.com/iotaledger/goshimmer/plugins/peer.configureLocalPeer
```

### PR DESCRIPTION
**Pull request by legacycode**
# Description of change

This PR flushes the updated seed to the peerdb. It fixes #303.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Please refer to #303 Reposteps.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: autopeering/peer/peerdb.go [hunk 1]
```diff
@@ -181,7 +181,11 @@ func (db *DB) LocalPrivateKey() (privateKey ed25519.PrivateKey, err error) {
 
 // UpdateLocalPrivateKey stores the provided key in the database.
 func (db *DB) UpdateLocalPrivateKey(key ed25519.PrivateKey) error {
-	return db.store.Set(localFieldKey(dbLocalKey), key.Bytes())
+	err := db.store.Set(localFieldKey(dbLocalKey), key.Bytes())
+	if err != nil {
```
Comment (muXxer) [inline autopeering/peer/peerdb.go:185]: Hey!
Thanks for the issue report and the fix!
Can you change the following? :)

```suggestion
	if err := db.store.Set(localFieldKey(dbLocalKey), key.Bytes()); err != nil {
```

**Review by muXxer — CHANGES_REQUESTED** [review]

File: autopeering/peer/peerdb.go (hunk 1 above)
Comment (legacycode) [reply autopeering/peer/peerdb.go]: Done

**Review by muXxer — APPROVED** [review]

**Comment by muXxer** [comment]
Thank you very much! Good catch! :)
Fixes #303
